Update docker_run.yml

diff --git a/.github/workflows/docker_run.yml b/.github/workflows/docker_run.yml
--- a/.github/workflows/docker_run.yml
+++ b/.github/workflows/docker_run.yml
@@ -109,6 +109,24 @@ jobs:
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
+            python /app/Validation/RandomForest.py && \
+            (echo 'Subject: GitHub Actions - Training/RandomForest.py Succeeded' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'Validation/RandomForest.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
+            (echo 'Subject: GitHub Actions - Validation/RandomForest.py Failed' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'Validation/RandomForest.py has failed.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
+
             python /app/Training/XGBoost.py && \
             (echo 'Subject: GitHub Actions - Training/XGBoost.py Succeeded' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
