train_validation_pipeline_success_failure_cases

diff --git a/.github/workflows/docker_run.yml b/.github/workflows/docker_run.yml
--- a/.github/workflows/docker_run.yml
+++ b/.github/workflows/docker_run.yml
@@ -55,7 +55,15 @@ jobs:
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
-            python Validation/Prophet.py || \
+            python /app/Validation/Prophet.py && \
+            (echo 'Subject: GitHub Actions - Validation/Prophet.py Succeeded' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'Validation/Prophet.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
             (echo 'Subject: GitHub Actions - Validation/Prophet.py Failed' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
             echo 'Validation/Prophet.py has failed.' >> email.txt && \
@@ -65,7 +73,15 @@ jobs:
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
-            python Training/RandomForest.py || \
+            python /app/Training/RandomForest.py && \
+            (echo 'Subject: GitHub Actions - Training/RandomForest.py Succeeded' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'Training/RandomForest.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
             (echo 'Subject: GitHub Actions - Training/RandomForest.py Failed' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
             echo 'Training/RandomForest.py has failed.' >> email.txt && \
@@ -75,17 +91,33 @@ jobs:
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
-            python Validation/RandomForest.py || \
-            (echo 'Subject: GitHub Actions - Validation/RandomForest.py Failed' > email.txt && \
+            python /app/Training/RandomForest.py && \
+            (echo 'Subject: GitHub Actions - Training/RandomForest.py Succeeded' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
-            echo 'Validation/RandomForest.py has failed.' >> email.txt && \
+            echo 'Training/RandomForest.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
+            (echo 'Subject: GitHub Actions - Training/RandomForest.py Failed' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'Training/RandomForest.py has failed.' >> email.txt && \
             curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
               --mail-from '$EMAIL_USERNAME' \
               --mail-rcpt '$RECIPIENT_EMAIL' \
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
-            python Training/XGBoost.py || \
+            python /app/Training/XGBoost.py && \
+            (echo 'Subject: GitHub Actions - Training/XGBoost.py Succeeded' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'Training/XGBoost.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
             (echo 'Subject: GitHub Actions - Training/XGBoost.py Failed' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
             echo 'Training/XGBoost.py has failed.' >> email.txt && \
@@ -95,7 +127,15 @@ jobs:
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
-            python Validation/XGBoost.py || \
+            python /app/Validation/XGBoost.py && \
+            (echo 'Subject: GitHub Actions - Validation/XGBoost.py Succeeded' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'Validation/XGBoost.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
             (echo 'Subject: GitHub Actions - Validation/XGBoost.py Failed' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
             echo 'Validation/XGBoost.py has failed.' >> email.txt && \
@@ -105,7 +145,15 @@ jobs:
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
-            python ModelBias/Model_bias.py || \
+            python /app/ModelBias/Model_bias.py && \
+            (echo 'Subject: GitHub Actions - ModelBias/Model_bias.py Succeeded' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'ModelBias/Model_bias.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
             (echo 'Subject: GitHub Actions - ModelBias/Model_bias.py Failed' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
             echo 'ModelBias/Model_bias.py has failed.' >> email.txt && \
@@ -115,7 +163,15 @@ jobs:
               --upload-file email.txt \
               --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
 
-            python bestmodel.py || \
+            python /app/bestmodel.py && \
+            (echo 'Subject: GitHub Actions - bestmodel.py Succeeded' > email.txt && \
+            echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
+            echo 'bestmodel.py has completed successfully.' >> email.txt && \
+            curl --url 'smtp://$SMTP_SERVER:$SMTP_PORT' --ssl-reqd \
+              --mail-from '$EMAIL_USERNAME' \
+              --mail-rcpt '$RECIPIENT_EMAIL' \
+              --upload-file email.txt \
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD') || \
             (echo 'Subject: GitHub Actions - bestmodel.py Failed' > email.txt && \
             echo 'To: $RECIPIENT_EMAIL' >> email.txt && \
             echo 'bestmodel.py has failed.' >> email.txt && \
@@ -123,7 +179,7 @@ jobs:
               --mail-from '$EMAIL_USERNAME' \
               --mail-rcpt '$RECIPIENT_EMAIL' \
               --upload-file email.txt \
-              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1)
+              --user '$EMAIL_USERNAME:$EMAIL_PASSWORD' && exit 1) && \
           "
 
       # Step 5: Cleanup - Stop and remove the container after all scripts complete
